import { Balance, Disputes, Payouts, Transactions } from "./shopify-payments";
import { AccessScopes, StorefrontAccessTokens } from "./access";
import { Reports } from "./analytics";
import { ApplicationCharges, ApplicationCredits, RecurringApplicationCharges } from "./billing";
import { Customers, CustomerSavedSearches } from "./customers";
import { PriceRules } from "./discounts";
import { Events, Webhooks } from "./events";
import { InventoryItems, InventoryLevels, Locations } from "./inventory";
import { MarketingEvents } from "./marketing-event";
import { Metafields } from "./metafield";
import { Articles, Blogs, Comments, Pages, Redirects, ScriptTags, Themes } from "./online-store";
import { Orders, Checkouts, DraftOrders } from "./orders";
import { Products, Collects, CustomCollections, SmartCollections } from "./products";
import { Shop, Country, ShippingZone, Currency, Policy } from "./store-properties";
declare const _default: {
    Balance: typeof Balance;
    Disputes: typeof Disputes;
    Payouts: typeof Payouts;
    Transactions: typeof Transactions;
    AccessScopes: typeof AccessScopes;
    StorefrontAccessTokens: typeof StorefrontAccessTokens;
    Reports: typeof Reports;
    ApplicationCharges: typeof ApplicationCharges;
    ApplicationCredits: typeof ApplicationCredits;
    RecurringApplicationCharges: typeof RecurringApplicationCharges;
    Customers: typeof Customers;
    CustomerSavedSearches: typeof CustomerSavedSearches;
    PriceRules: typeof PriceRules;
    Events: typeof Events;
    Webhooks: typeof Webhooks;
    InventoryItems: typeof InventoryItems;
    InventoryLevels: typeof InventoryLevels;
    Locations: typeof Locations;
    MarketingEvents: typeof MarketingEvents;
    Metafields: typeof Metafields;
    Articles: typeof Articles;
    Blogs: typeof Blogs;
    Comments: typeof Comments;
    Pages: typeof Pages;
    Redirects: typeof Redirects;
    ScriptTags: typeof ScriptTags;
    Themes: typeof Themes;
    Orders: typeof Orders;
    Checkouts: typeof Checkouts;
    DraftOrders: typeof DraftOrders;
    Products: typeof Products;
    Collects: typeof Collects;
    CustomCollections: typeof CustomCollections;
    SmartCollections: typeof SmartCollections;
    Shop: typeof Shop;
    Country: typeof Country;
    ShippingZone: typeof ShippingZone;
    Currency: typeof Currency;
    Policy: typeof Policy;
};
export default _default;
